export const defaultIndianStates = [
  { code: "AN", label: "Andaman and Nicobar Islands", sortOrder: 1 },
  { code: "AP", label: "Andhra Pradesh", sortOrder: 2 },
  { code: "AR", label: "Arunachal Pradesh", sortOrder: 3 },
  { code: "AS", label: "Assam", sortOrder: 4 },
  { code: "BR", label: "Bihar", sortOrder: 5 },
  { code: "CH", label: "Chandigarh", sortOrder: 6 },
  { code: "CT", label: "Chhattisgarh", sortOrder: 7 },
  {
    code: "DN",
    label: "Dadra and Nagar Haveli and Daman and Diu",
    sortOrder: 8,
  },
  { code: "DL", label: "Delhi", sortOrder: 9 },
  { code: "GA", label: "Goa", sortOrder: 10 },
  { code: "GJ", label: "Gujarat", sortOrder: 11 },
  { code: "HR", label: "Haryana", sortOrder: 12 },
  { code: "HP", label: "Himachal Pradesh", sortOrder: 13 },
  { code: "JK", label: "Jammu and Kashmir", sortOrder: 14 },
  { code: "JH", label: "Jharkhand", sortOrder: 15 },
  { code: "KA", label: "Karnataka", sortOrder: 16 },
  { code: "KL", label: "Kerala", sortOrder: 17 },
  { code: "LA", label: "Ladakh", sortOrder: 18 },
  { code: "LD", label: "Lakshadweep", sortOrder: 19 },
  { code: "MP", label: "Madhya Pradesh", sortOrder: 20 },
  { code: "MH", label: "Maharashtra", sortOrder: 21 },
  { code: "MN", label: "Manipur", sortOrder: 22 },
  { code: "ML", label: "Meghalaya", sortOrder: 23 },
  { code: "MZ", label: "Mizoram", sortOrder: 24 },
  { code: "NL", label: "Nagaland", sortOrder: 25 },
  { code: "OD", label: "Odisha", sortOrder: 26 },
  { code: "PY", label: "Puducherry", sortOrder: 27 },
  { code: "PB", label: "Punjab", sortOrder: 28 },
  { code: "RJ", label: "Rajasthan", sortOrder: 29 },
  { code: "SK", label: "Sikkim", sortOrder: 30 },
  { code: "TN", label: "Tamil Nadu", sortOrder: 31 },
  { code: "TG", label: "Telangana", sortOrder: 32 },
  { code: "TR", label: "Tripura", sortOrder: 33 },
  { code: "UP", label: "Uttar Pradesh", sortOrder: 34 },
  { code: "UT", label: "Uttarakhand", sortOrder: 35 },
  { code: "WB", label: "West Bengal", sortOrder: 36 },
] as const;
